### ISSUE TITLE
Use api token instead of login/password

### ISSUE THREAD

**Issue by dtrckd** [peterhellberg/neocities#6]
Hi,
Would it be possible to use the token provided by neocities instead of the login/passw ?
Thanks.

**Comment by peterhellberg** [comment]
@dtrckd Yes, this is a good idea for an improvement to this project. I’ll see what I can do about it.

**Comment by peterhellberg** [comment]
@dtrckd Please try out the new API Key functionality.

```sh
NEOCITIES_USER=<your user> NEOCITIES_PASS=<your password> neocities key
```

Should return an API key that you then can use like this:

```sh
NEOCITIES_KEY=<your key> neocities info
```

**Comment by dtrckd** [comment]
It works! Very nice, thanks ! 

PS:
when typing `neocities` without credentials, it outputs: 
`Error: Missing environment variable NEOCITIES_USER`

Maybe the message can updated to have: 
`Error: Missing environment variable NEOCITIES_USER or NEOCITIES_USER `

Cheers.
Maybe,

**Comment by peterhellberg** [comment]
@dtrckd Yeah, that sounds like a good idea.
