### ISSUE TITLE
push 

### ISSUE THREAD

**Issue by 3052** [peterhellberg/neocities#7]
is push available?

~~~
push        Recursively upload a local directory to your site
~~~

https://neocities.org/cli

**Comment by peterhellberg** [comment]
@3052 Note that this is **not** the https://neocities.org/cli Ruby gem, but my own little CLI written in Go.

I do not have a `push` command, just `upload` that takes a list of files to upload.

**Comment by 3052** [comment]
I found another tool that does push

https://github.com/kugland/neocities-deploy
